package com.fengli.video.mapper;

import com.fengli.video.pojo.Bgm;
import com.fengli.video.pojo.BgmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BgmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated
     */
    int countByExample(BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated
     */
    int deleteByExample(BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated
     */
    int insert(Bgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated
     */
    int insertSelective(Bgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated
     */
    List<Bgm> selectByExample(BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Bgm record, @Param("example") BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Bgm record, @Param("example") BgmExample example);
}