package com.fengli.video.mapper;

import com.fengli.video.pojo.Search_records;
import com.fengli.video.pojo.Search_recordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Search_recordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbggenerated
     */
    int countByExample(Search_recordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbggenerated
     */
    int deleteByExample(Search_recordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbggenerated
     */
    int insert(Search_records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbggenerated
     */
    int insertSelective(Search_records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbggenerated
     */
    List<Search_records> selectByExample(Search_recordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Search_records record, @Param("example") Search_recordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_records
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Search_records record, @Param("example") Search_recordsExample example);
}