package com.fengli.video.mapper;

import com.fengli.video.pojo.Users_like_videos;
import com.fengli.video.pojo.Users_like_videosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Users_like_videosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbggenerated
     */
    int countByExample(Users_like_videosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbggenerated
     */
    int deleteByExample(Users_like_videosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbggenerated
     */
    int insert(Users_like_videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbggenerated
     */
    int insertSelective(Users_like_videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbggenerated
     */
    List<Users_like_videos> selectByExample(Users_like_videosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Users_like_videos record, @Param("example") Users_like_videosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_like_videos
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Users_like_videos record, @Param("example") Users_like_videosExample example);
}