package com.fengli.video.mapper;

import com.fengli.video.pojo.Users_report;
import com.fengli.video.pojo.Users_reportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Users_reportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbggenerated
     */
    int countByExample(Users_reportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbggenerated
     */
    int deleteByExample(Users_reportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbggenerated
     */
    int insert(Users_report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbggenerated
     */
    int insertSelective(Users_report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbggenerated
     */
    List<Users_report> selectByExample(Users_reportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Users_report record, @Param("example") Users_reportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Users_report record, @Param("example") Users_reportExample example);
}