package com.fengli.video.mapper;

import com.fengli.video.pojo.Users_fans;
import com.fengli.video.pojo.Users_fansExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Users_fansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int countByExample(Users_fansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int deleteByExample(Users_fansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int insert(Users_fans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int insertSelective(Users_fans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    List<Users_fans> selectByExample(Users_fansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Users_fans record, @Param("example") Users_fansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Users_fans record, @Param("example") Users_fansExample example);
}